server:
  port: 8882
eureka:
  client:
#    registryWithEureka: true
#    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8881/eureka/
#    instance:
#      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sg-customer
          uri: http://localhost:8999/api/v1/customers
          predicates:
            - Path=/api/v1/customers/**
         
  #application:
  #  name: registry-service          