server:
  port: 8882
eureka:
  client:
#    registryWithEureka: true
#    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8881/eureka/
#    instance:
#      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sg-customer
          uri: http://localhost:8999/api/v1/customers
          predicates:
            - Path=/api/v1/customers/**
        - id: sg-product
          uri: http://localhost:8991/api/v1/products
          predicates:
            - Path=/api/v1/products/**   
        - id: sg-banking-movements
          uri: http://localhost:8992/api/v1/movements
          predicates:
            - Path=/api/v1/movements/** 
          uri: http://localhost:8992/api/v1/banking-operation
          predicates:
            - Path=/api/v1/banking-operation**       
         
  #application:
  #  name: registry-service          