server:
  port: 8992


spring:
  data:
    mongodb:
      database: movementsDB
      port: '27017'
      host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/
      
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true


resilience4j.circuitbreaker:
  instances:
    find-product:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 50s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10      
